export const note = [
  {
    id: 1,
    topic: "1.1.1 Teknik dalam Pemikiran Komputasional",
    desc: "desc1",
    video: "../../assets/videos/sample.mp4",
    note: "../../assets/notes/note1/nota1.pdf",
    images: [
      "../../assets/notes/note1/1.png",
      "../../assets/notes/note1/2.png",
      "../../assets/notes/note1/3.png",
      "../../assets/notes/note1/4.png",
      "../../assets/notes/note1/5.png",
      "../../assets/notes/note1/6.png",
    ],
  },
  {
    id: 2,
    topic:
      "1.1.2 Penggunaan Teknik Leraian dan Menentukan Langkah Secara Tertib",
    desc: "desc2",
    video: "../../assets/videos/sample2.mp4",
    note: "../../assets/notes/note2/nota2.pdf",
    images: [
      "../../assets/notes/note2/1.png",
      "../../assets/notes/note2/2.png",
      "../../assets/notes/note2/3.png",
      "../../assets/notes/note2/4.png",
      "../../assets/notes/note2/5.png",
    ],
  },
  {
    id: 3,
    topic: "1.1.3 Pengecaman Coak dalam Sesuatu Situasi",
    desc: "desc3",
    video: "../../assets/videos/sample.mp4",
    note: "../../assets/notes/note3/nota3.pdf",
    images: [
      "../../assets/notes/note3/1.png",
      "../../assets/notes/note3/2.png",
      "../../assets/notes/note3/3.png",
      "../../assets/notes/note3/4.png",
      "../../assets/notes/note3/5.png",
      "../../assets/notes/note3/6.png",
    ],
  },
  {
    id: 4,
    topic: "1.1.4 Membuat Keputusan Berdasarkan Aspek Penting",
    desc: "desc4",
    video: "../../assets/videos/sample2.mp4",
    note: "../../assets/notes/note4/nota4.pdf",
    images: [
      "../../assets/notes/note4/1.png",
      "../../assets/notes/note4/2.png",
      "../../assets/notes/note4/3.png",
      "../../assets/notes/note4/4.png",
      "../../assets/notes/note4/5.png",
      "../../assets/notes/note4/6.png",
    ],
  },
  {
    id: 5,
    topic: "1.1.5 Ciri-Ciri Kesamaan dalam Sesuatu Permasalahan",
    desc: "desc5",
    video: "../../assets/videos/sample.mp4",
    note: "../../assets/notes/note5/nota5.pdf",
    images: [
      "../../assets/notes/note5/1.png",
      "../../assets/notes/note5/2.png",
      "../../assets/notes/note5/3.png",
      "../../assets/notes/note5/4.png",
      "../../assets/notes/note5/5.png",
      "../../assets/notes/note5/6.png",
      "../../assets/notes/note5/7.png",
      "../../assets/notes/note5/8.png",
      "../../assets/notes/note5/9.png",
      "../../assets/notes/note5/10.png",
      "../../assets/notes/note5/11.png",
    ],
  },
];
